### ISSUE TITLE
Other sample data to test

### ISSUE THREAD

**Issue by greggish** [openreferral/hsds-transformer#5]
We recently had a set of sample data that came without a datapackage (and, also, I think some of the relationships between fields may not be carefully defined). So you can test with some of Florida's legal aid providers: https://drive.google.com/drive/folders/1UghRs1TnyrhgoVj-s6P0XqtA0Ic8erEl

(FYI, please only use this data for a transformation test, it's already out of date and incomplete, and wasn't intended for like publishing on the internet.)

**Comment by switzersc** [comment]
We tested with this data back in Feb/March and it all looks good!
