### ISSUE TITLE
Airtable link

### ISSUE THREAD

**Issue by bdsharmaco** [openreferral/hsds-transformer#50]
Hi, it seems the airtable link https://airtable.com/universe/expTMdQFD5r9G6V9Y/open-referral-human-services-template doesn't resolve and brings up a 404 for me? I have tried this while logged in as well. 
For context, I am looking at how we align the Leeds LOOP (repository) to openreferral, and adopt it with contributions to support the city's services, information and local 'language'

**Comment by devinbalkind** [comment]
Here's the right link: https://airtable.com/tblFeE7TApve3iCxS/viw6v6AwusCrxR5up?blocks=hide

**Comment by greggish** [comment]
Thanks for bringing this to our attention, @bdsharmaco. I just replaced the link with this one - https://airtable.com/universe/expwt9yr65lFGUJAr/social-services-directory-v20

By the way, I will be in the UK starting at the end of this week, thru Feb 3rd. I'll be connecting with others who are implementing Open Referral there. It would be great to learn more about your project and see how i might help!
